[package]
name = "goida_lang"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
string-interner = "0.14"
lalrpop-util = { version = "0.22.2", features = ["lexer"] }

[build-dependencies]
lalrpop = "0.22.2"