[package]
name = "goida_lang"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
string-interner = "0.19.0"
pest = { version = "2.8.5" }
pest_derive = { version = "2.8.5" }
ariadne = { version = "0.6.0" }
lazy_static = "1.5.0"